name: 'Release'
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_FOLDER: build

    steps:
      - name: Install WP CLI
        id: install-wp-cli
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar --info
          php wp-cli.phar package install wp-cli/dist-archive-command

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: ${{ env.BUILD_FOLDER }}
          ref: ${{ github.ref }}

      - name: Composer
        working-directory: ${{ env.BUILD_FOLDER }}
        run: |
          composer install --no-dev
          cd ..
          pwd
          php wp-cli.phar dist-archive build


