name: 'Release'
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_FOLDER: build
      PLUGIN_SLUG: actions

    steps:
      - name: Install WP CLI
        id: install-wp-cli
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar --info
          php wp-cli.phar package install wp-cli/dist-archive-command

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: ${{ env.BUILD_FOLDER }}
          ref: ${{ github.ref }}

      - name: Composer
        working-directory: ${{ env.BUILD_FOLDER }}
        run: |
          composer install --no-dev
          cd ..
          php wp-cli.phar dist-archive ${{ env.BUILD_FOLDER }} --plugin-dirname=${{ env.PLUGIN_SLUG }}
          echo "${{ github.event.release }}"
          echo "${{ github.event.release.prerelease }}"

      - name: Save to Release
        uses: xresloader/upload-to-github-release@v1
        if: ${{ github.event.release.prerelease == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.zip"
          tags: true
